### ISSUE TITLE
yarn install failing

### ISSUE THREAD

**Issue by wayneashleyberry** [GoogleCloudPlatform/nodejs-docker#109]
Deployments just started breaking for me, removing the `yarn.lock` file (thus falling back to npm) fixes the issue.

```
------------------------------------------------------------- REMOTE BUILD OUTPUT --------------------------------------------------------------
starting build "f5777c6f-a89e-4157-8b8f-9bd45e4b710a"

FETCHSOURCE
Fetching storage object: **************
Copying **************
/ [1 files][ 41.4 KiB/ 41.4 KiB]
Operation completed over 1 objects/41.4 KiB.
BUILD
Already have image (with digest): gcr.io/cloud-builders/docker
Sending build context to Docker daemon  153.1kB
Step 1/6 : FROM gcr.io/google_appengine/nodejs
latest: Pulling from google_appengine/nodejs
Digest: sha256:6a64421faec21d78e0bc18f7aebce959cd9c39d1f0561de1573f57c35a536a2e
Status: Downloaded newer image for gcr.io/google_appengine/nodejs:latest
 ---> 58335b41babb
Step 2/6 : RUN /usr/local/bin/install_node 8.x
 ---> Running in 7c1d569546d3
Installed Node.js v8.1.3
 ---> 9c8b0aac7865
Removing intermediate container 7c1d569546d3
Step 3/6 : RUN npm install --unsafe-perm --global yarn
 ---> Running in c72adcdce2bc
/nodejs/bin/yarn -> /nodejs/lib/node_modules/yarn/bin/yarn.js
/nodejs/bin/yarnpkg -> /nodejs/lib/node_modules/yarn/bin/yarn.js
+ yarn@0.27.5
added 201 packages in 10.138s
 ---> 816ddcbc8f1f
Removing intermediate container c72adcdce2bc
Step 4/6 : COPY . /app/
 ---> 8202341384f7
Removing intermediate container 9fe5a82cdf3d
Step 5/6 : RUN yarn install --production ||   ((if [ -f yarn-error.log ]; then       cat yarn-error.log;     fi) && false)
 ---> Running in db1886fc43a4
/nodejs/lib/node_modules/yarn/lib/cli/commands/index.js:322
  commands[key].getDocsInfo = getDocsInfo(key);
                            ^

TypeError: Cannot set property 'getDocsInfo' of undefined
    at Object.<anonymous> (/nodejs/lib/node_modules/yarn/lib/cli/commands/index.js:322:29)
    at Module._compile (/nodejs/lib/node_modules/yarn/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (/nodejs/lib/node_modules/yarn/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at _load_index3 (/nodejs/lib/node_modules/yarn/lib/cli/index.js:18:43)
    at Object.<anonymous> (/nodejs/lib/node_modules/yarn/lib/cli/index.js:136:54)
The command '/bin/sh -c yarn install --production ||   ((if [ -f yarn-error.log ]; then       cat yarn-error.log;     fi) && false)' returned a non-zero code: 1
ERROR
ERROR: build step "gcr.io/cloud-builders/docker@sha256:89f13e6f1703d07a8b61d054167b4333491ddddbbf57dec1a117cd1437b09a9e" failed: exit status 1

ERROR: (gcloud.app.deploy) Error Response: [2] Build failed; check build logs for details
```

**Comment by Arrow7000** [comment]
I am getting the exact same error. Subscribed.

**Comment by ofrobots** [comment]
As an experiment, can you try the beta deploy command and see if that gives you different results:

```shell
$ gcloud beta app deploy [rest of your app deploy options]
```

**Comment by ofrobots** [comment]
Related https://github.com/yarnpkg/yarn/issues/3851

**Comment by ofrobots** [comment]
I believe this was an issue in one of the dependencies of yarn. This should be fixed now upstream now. `gcloud beta app deploy` would have worked around the issue as it uses the version of `yarn` preinstalled in the docker image (0.24.x as of this writing) instead of installing the latest version of `yarn`.

Closing. Please re-open if this is still an issue.

**Comment by wayneashleyberry** [comment]
Thanks @ofrobots, `beta deploy` does the trick for now.
